spring.application.name=Backend

spring.datasource.url=jdbc:postgresql://ep-billowing-bar-a1opx0a6-pooler.ap-southeast-1.aws.neon.tech/rellet-ai?user=neondb_owner&password=npg_w71EuDQkbscF&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owne
spring.datasource.password=npg_w71EuDQkbscF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
